# jekyll-paginate configuration
paginate: 5
paginate_path: "/:num"

# Site settings
title: Quantum Untangled
description: An open-source community making quantum computing accesible.
baseurl: ""
url: "https://www.quantumuntangled.org"

# Build settings
markdown:    kramdown
highlighter: rouge
permalink:   none
plugins:     [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Sass settings
sass:
  sass_dir: assets/css
  style: :nested